module PropertyType
    HOME_POST_CODE                          = "HOME_POST_CODE"          # Text
    HOME_CITY                               = "HOME_CITY"               # Text
    HOME_ADDRESS1                           = "HOME_ADDRESS1"           # Text
    HOME_ADDRESS2                           = "HOME_ADDRESS2"           # Text
    HOME_ADDRESS3                           = "HOME_ADDRESS3"           # Text
    HOME_STATE                              = "HOME_STATE"              # Text
    HOME_COUNTRY_CODE                       = "HOME_COUNTRY_CODE"       # Country code (ISO-3166)
    FIRST_NAME                              = "FIRST_NAME"              # Text
    MIDDLE_NAME                             = "MIDDLE_NAME"             # Text
    LAST_NAME                               = "LAST_NAME"               # Text
    TITLE                                   = "TITLE"                   # Mr/Mrs/Ms/Dr/Sir
    PHONE                                   = "PHONE"                   # +CountryCodePhoneNumber
    DOB                                     = "DOB"			# YYYY-MM-DD-T22:00:00.000Z
    POB                                     = "POB"                     # Text
    NATIONALITY                             = "NATIONALITY"             # Country code (ISO-3166)
    PROFILEPIC                              = "PROFILEPIC"
    NAMESPACE                               = "NAMESPACE"               # Alpha-numeric text		
    REQUESTER_LAT                           = "REQUESTER_LAT"
    REQUESTER_LNG                           = "REQUESTER_LNG"
    RESPONDER_LAT                           = "RESPONDER_LAT"
    RESPONDER_LNG                           = "RESPONDER_LNG"
    SET_PHOTO_IDS                           = "SET_PHOTO_IDS"
    SET_ADDRESS_VALIDATION_IDS              = "SET_ADDRESS_VALIDATION_IDS"
    SIGNED_TOKEN_ID                         = "SIGNED_TOKEN_ID"
    TOKEN_SIGNATURE_PUBLIC_KEY              = "TOKEN_SIGNATURE_PUBLIC_KEY"
    TOKEN_SIGNATURE_VERIFICATION_RESULT     = "TOKEN_SIGNATURE_VERIFICATION_RESULT"
    WEB_ACCESS_NONCE                        = "WEB_ACCESS_NONCE"
    WEB_ACCESS_SIGNED_NONCE                 = "WEB_ACCESS_SIGNED_NONCE"
    WEB_ACCESS_BROWSER_ECDH_PUB_KEY         = "WEB_ACCESS_BROWSER_ECDH_PUB_KEY"
    WEB_ACCESS_SERVICE_ECDH_PUB_KEY         = "WEB_ACCESS_SERVICE_ECDH_PUB_KEY"
    WEB_ACCESS_PHONE_ECDH_PUB_KEY           = "WEB_ACCESS_PHONE_ECDH_PUB_KEY"
    WEB_ACCESS_SERVICE_PASSPHRASE_CIPHER    = "WEB_ACCESS_SERVICE_PASSPHRASE_CIPHER"
    WEB_ACCESS_SERVICE_PASSPHRASE_CIPHER_IV = "WEB_ACCESS_SERVICE_PASSPHRASE_CIPHER_IV"
    WEB_ACCESS_BROWSER_PASSPHRASE_CIPHER_IV = "WEB_ACCESS_BROWSER_PASSPHRASE_CIPHER_IV"
end
