module ECPublicKeyFormats
    HEXADECIMAL                   = "HEXADECIMAL"
    XY_HEXADECIMAL                = "XY_HEXADECIMAL"
    BASE_64_ENCODED_DER           = "BASE_64_ENCODED_DER"
    PEM_STRING                    = "PEM_STRING"
    PASSWORD_PROTECTED_PEM_STRING = "PASSWORD_PROTECTED_PEM_STRING" 
end
